// Command kitsources writes the Tailwind @source line that points at this kit's
// templates.
//
// Tailwind only generates the classes it can see, and the kit's templates live
// at a module path with a version in it — a module cache directory on one
// machine, a go.work checkout on another. @source takes no variable, so the line
// has to be generated, and every consumer was generating it with an identical
// copy of the same shell script.
//
// Shipping it here means a consumer runs
//
//	go run github.com/msrsiddik/apicorex-ui/cmd/kitsources -o internal/web/static/css/kit-sources.css
//
// and copies nothing. It resolves the kit's directory from the caller's own
// module graph, so it is right whether the kit came from the cache or a
// workspace checkout.
//
// Get this wrong and every class the kit uses is stripped as unused: the page
// compiles, deploys, and renders completely unstyled, with nothing failing
// anywhere. Check the built stylesheet's size in CI.
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

const module = "github.com/msrsiddik/apicorex-ui"

func main() {
	out := flag.String("o", "", "file to write (default: stdout)")
	flag.Parse()

	dir, err := kitDir()
	if err != nil {
		fmt.Fprintln(os.Stderr, "kitsources:", err)
		os.Exit(1)
	}

	line := fmt.Sprintf(
		"/* Generated by %s/cmd/kitsources — do not edit, and do not commit.\n"+
			"   Points Tailwind at the shared UI kit's templates at their resolved path. */\n"+
			"@source \"%s/components/**/*.templ\";\n", module, dir)

	if *out == "" {
		fmt.Print(line)
		return
	}
	if err := os.WriteFile(*out, []byte(line), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "kitsources:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "kit sources -> %s/components\n", dir)
}

// kitDir asks the caller's module graph where the kit ended up.
func kitDir() (string, error) {
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", module)
	outBytes, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("locating %s: %w", module, err)
	}
	dir := strings.TrimSpace(string(outBytes))
	if dir == "" {
		return "", fmt.Errorf("%s resolved to no directory", module)
	}
	return dir, nil
}
